# Generated by Django 5.2.5 on 2025-08-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_status_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Имя'),
        ),
    ]
